# Generated by Django 4.1.3 on 2022-11-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Khoj_The_Search', '0003_alter_valuelist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valuelist',
            old_name='value_list',
            new_name='input_values',
        ),
        migrations.RenameField(
            model_name='valuelist',
            old_name='created',
            new_name='timestamp',
        ),
    ]
